document.addEventListener("DOMContentLoaded",()=>{
    const form=document.querySelector('.appointment-form');const table=document.querySelector('.patient-table tbody');const cards=[...document.querySelectorAll('.cards .card')];let reports=[],patients=[],doctors=[];
    const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
    async function load(){try{const [r,p,u,st]=await Promise.all([apiRequest('/reports?limit=100'),apiRequest('/patients?limit=100'),apiRequest('/auth/doctors'),apiRequest('/reports/stats')]);reports=r.reports||[];patients=p.patients||[];doctors=u.users||[];render();const x=st.statistics||st.stats||{};const vals=[r.totalReports??reports.length,x.downloads??0,x.accuracy??'—',reports.filter(r=>r.reportStatus!=='Completed').length];cards.forEach((c,i)=>{const h=c.querySelector('h2');if(h)h.textContent=vals[i]??0});populate();}catch(e){if(table)table.innerHTML=`<tr><td colspan="7"><div class="cs-error">${esc(e.message)}</div></td></tr>`}}
    function populate(){const selects=form?.querySelectorAll('select');if(!selects?.length)return;selects[0].innerHTML='<option value="">All Departments</option>'+[...new Set(patients.map(p=>p.department).filter(Boolean))].map(x=>`<option>${esc(x)}</option>`).join('');}
    function render(){if(!table)return;table.innerHTML=reports.length?reports.map(r=>`<tr><td>${esc(r.reportId)}</td><td>${esc(r.reportTitle)}</td><td>${esc(r.patient?`${r.patient.firstName} ${r.patient.lastName}`:'—')}</td><td>${esc(r.doctor?.fullName||'—')}</td><td>${esc(r.reportType)}</td><td><span class="status-badge">${esc(r.reportStatus)}</span></td><td><button class="cs-btn-small" data-view="${r._id}">View</button></td></tr>`).join(''):'<tr><td colspan="7"><div class="cs-empty">No reports found.</div></td></tr>';table.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view))}
    function view(id){const r=reports.find(x=>x._id===id);if(r)alert(`${r.reportTitle}\n\nPatient: ${r.patient?.firstName||''} ${r.patient?.lastName||''}\nDoctor: ${r.doctor?.fullName||''}\nType: ${r.reportType}\nStatus: ${r.reportStatus}\n\nDiagnosis: ${r.diagnosis||'—'}\nFindings: ${r.findings||'—'}\nRemarks: ${r.remarks||'—'}`)}
    function openModal(){const b=document.createElement('div');b.className='cs-modal-backdrop';b.innerHTML=`<div class="cs-modal"><button class="cs-close">×</button><h2>Create Medical Report</h2><p class="muted">Save a report directly to CareScope.</p><form id="reportCreateForm"><div class="cs-form-grid"><div class="cs-field"><label>Patient *</label><select name="patient" required><option value="">Select patient</option>${patients.map(p=>`<option value="${p._id}">${esc(p.firstName)} ${esc(p.lastName)} — ${esc(p.patientId)}</option>`).join('')}</select></div><div class="cs-field"><label>Doctor *</label><select name="doctor" required><option value="">Select doctor</option>${doctors.map(d=>`<option value="${d._id}">${esc(d.fullName)}</option>`).join('')}</select></div><div class="cs-field"><label>Title *</label><input name="reportTitle" required placeholder="e.g. Blood Test Report"></div><div class="cs-field"><label>Type</label><select name="reportType"><option>Blood Test</option><option>X-Ray</option><option>MRI</option><option>CT Scan</option><option>ECG</option><option>Prescription</option><option>Discharge Summary</option><option>Medical Certificate</option><option>Other</option></select></div><div class="cs-field"><label>Status</label><select name="reportStatus"><option>Pending</option><option>Processing</option><option>Completed</option></select></div><div class="cs-field"><label>Diagnosis</label><input name="diagnosis"></div><div class="cs-field full"><label>Findings</label><textarea name="findings"></textarea></div><div class="cs-field full"><label>Remarks</label><textarea name="remarks"></textarea></div></div><div class="cs-modal-actions"><button type="button" class="cs-btn secondary" id="cancelReport">Cancel</button><button class="cs-btn primary">Submit Report</button></div></form></div>`;document.body.appendChild(b);const close=()=>b.remove();b.querySelector('.cs-close').addEventListener('click', close);b.querySelector('#cancelReport').addEventListener('click', close);b.addEventListener('click', e=>{if(e.target===b)close()});b.querySelector('form').addEventListener('submit', async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{await apiRequest('/reports',{method:'POST',body:JSON.stringify({...d,reportId:`REP${Date.now().toString().slice(-7)}`})});close();showToast('Report submitted successfully');load()}catch(err){showToast(err.message,'error')}});}
    const heroBtn=[...document.querySelectorAll('.hero-right button')].find(b=>/generate report/i.test(b.textContent));heroBtn?.addEventListener('click',openModal);form?.addEventListener('submit',e=>{e.preventDefault();openModal()});load();
});
